link:
  home: "#"
logo:
  img_size: 27
  img_size_home: 50
  txt: Cash flow system
  link: "logo.png"
  logo_txt: "Cash flow system"
image:
  link_user: "https://wsm.sun-asterisk.vn//assets/user_avatar_default-bc6c6c40940226d6cf0c35571663cd8d231a387d5ab1921239c2bd19653987b2.png"
  link_logo_wsm: "wsm-logo.ico"
  link_logo_wsm_size: 20
  user_img_size: 40
landing_page:
  text: " Tokyo International Airport"
validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    name_max_length: 50
    email_max_length: 255
    pass_min_length: 6
    user_per_page: 20
    size_ava: 50
    checkbox_checked: "1"
    admin_role: 1
    accountant_role: 2
    manager_role: 3
    user_role: 4
    accountant_manager: 5
  amout_min: 0
  supplier:
    tax_regex: !ruby/regexp '/\A\d{10}-\d{3}\z|\A\d{10}\z/'
pagination:
  items_per_pages: 15
  default_page: 1
title:
  max_length: 60
content:
  max_length: 140
status:
  request:
    pending: 1
    approved: 2
    paid: 3
    rejected: 4
    canceled: 5
  income:
    pending: 1
    approved: 2
    rejected: 3
    canceled: 4
