link:
  home: "#"
logo:
  img_size: 60
  txt: Cash flow system
  link: "cfs-logo.png"
image:
  link_user: "https://wsm.sun-asterisk.vn//assets/user_avatar_default-bc6c6c40940226d6cf0c35571663cd8d231a387d5ab1921239c2bd19653987b2.png"
  user_img_size: 40
