name: Rails CD

on: [push, pull_request]

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo gem install bundler:1.17.2
      - run: |
          bundle config path vendor/bundle
          bundle install
      - run : mkdir -p ~/.ssh
      - run : echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/private_key
      - run: chmod 600 ~/.ssh/private_key
      - name: Send file to server
        run: rsync -azhv -e 'ssh -i ~/.ssh/private_key -o StrictHostKeyChecking=no' . --rsync-path='sudo rsync -vha'  $user@$host:$target
        env:
          user: ubuntu
          host: 54.89.194.129
          target: /var/www/cash-flow-system
